# Copyright 2026 Darwin-Agent
# SPDX-License-Identifier: MIT
from pathlib import Path

import pytest

from harnessx.core.events import (
    BeforeModelEvent,
    Message,
    ModelResponseEvent,
    ProcessorTriggerEvent,
    StepEndEvent,
    StepStartEvent,
    ToolCall,
    ToolCallEvent,
    ToolResultEvent,
)
from harnessx.core.processor import pipe, pipe_all, MultiHookProcessor
from harnessx.core.runloop import (
    BudgetExceededError,
    LoopDetectedError,
    ModelParseError,
)
from harnessx.processors.control.bg_install_guard import BgInstallGuard
from harnessx.processors.control.cost_guard import CostGuardProcessor
from harnessx.processors.control.loop_detection import LoopDetectionProcessor
from harnessx.processors.control.parse_retry import ParseRetryProcessor
from harnessx.processors.control.repeated_edit_detector import RepeatedFileEditDetector
from harnessx.processors.control.self_verify import SelfVerifyProcessor
from harnessx.processors.control.token_budget import TokenBudgetProcessor
from harnessx.processors.control.tool_call_correction import ToolCallCorrectionLayer
from harnessx.processors.control.tool_failure_guard import (
    ToolFailureGuard,
    ToolFailureLimitError,
)
from harnessx.processors.control.todo_check import TodoCheck
from harnessx.processors.control.rl_signal import RLSignalCollectorProcessor
from harnessx.processors.control.sycophancy_detector import SycophancyDetector


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------


def _triggers(events: list) -> list[ProcessorTriggerEvent]:
    """Filter only ProcessorTriggerEvent entries from a pipe_all result."""
    return [e for e in events if isinstance(e, ProcessorTriggerEvent)]


class _RecordingTracer:
    """Minimal tracer that records ProcessorTriggerEvent auto-generated by ProcessorChain."""

    def __init__(self) -> None:
        self.trigger_events: list[ProcessorTriggerEvent] = []
        self.raw_events: list = []

    async def on_event(self, event) -> None:
        if isinstance(event, ProcessorTriggerEvent):
            self.trigger_events.append(event)

    async def on_raw_event(self, event) -> None:
        self.raw_events.append(event)


# =============================================================================
# LoopDetectionProcessor
# =============================================================================


async def _write_file(proc, path: str, call_id: str):
    """Simulate one Write call+result through the processor; return pipe_all result."""
    ce = ToolCallEvent(
        run_id="r1",
        step_id=0,
        tool_name="Write",
        tool_call_id=call_id,
        tool_input={"file_path": path},
    )
    await pipe(ce, [proc])
    return await pipe_all(
        ToolResultEvent(run_id="r1", step_id=0, tool_name="Write", tool_call_id=call_id, result="ok"),
        [proc],
    )


def _agree_event(run_id="r1", step_id=0) -> ModelResponseEvent:
    """Model response that matches the agreement regex."""
    return ModelResponseEvent(
        run_id=run_id,
        step_id=step_id,
        content="Absolutely! You're completely right about that.",
    )


class _MutatingProcessor(MultiHookProcessor):
    """Processor that silently mutates an event — ProcessorChain should auto-detect."""

    _singleton_group = "test_mutating"

    async def on_before_model(self, event: BeforeModelEvent):
        from harnessx.core.events import Message

        yield BeforeModelEvent(
            run_id=event.run_id,
            step_id=event.step_id,
            messages=event.messages + (Message(role="user", content="auto"),),
        )


class _PassthroughProcessor(MultiHookProcessor):
    """Processor that yields the event unchanged — no trigger should fire."""

    _singleton_group = "test_passthrough"

    async def on_before_model(self, event: BeforeModelEvent):
        yield event


_TODOS_MIX = [
    {"id": "1", "content": "Research topic", "status": "done"},
    {"id": "2", "content": "Write report", "status": "in_progress"},
    {"id": "3", "content": "Review draft", "status": "pending"},
]
_TODOS_ALL_DONE = [
    {"id": "1", "content": "Step A", "status": "done"},
    {"id": "2", "content": "Step B", "status": "done"},
]


class TestProcessorTriggers:
    @pytest.mark.asyncio
    async def test_loop_detection_warning_trigger(self):
        """warn_threshold=3: 3rd consecutive identical call injects loop warning into tool result."""
        proc = LoopDetectionProcessor(threshold=5, warn_threshold=3, window_size=10)
        for i in range(2):
            tc = ToolCallEvent(
                run_id="r1",
                step_id=i,
                tool_name="Bash",
                tool_call_id=f"c{i}",
                tool_input={"command": "ls"},
            )
            await pipe(tc, [proc])
            await pipe(
                ToolResultEvent(
                    run_id="r1",
                    step_id=i,
                    tool_name="Bash",
                    tool_call_id=f"c{i}",
                    result="ok",
                ),
                [proc],
            )
        # 3rd repeat → warn
        tc3 = ToolCallEvent(
            run_id="r1",
            step_id=2,
            tool_name="Bash",
            tool_call_id="c2",
            tool_input={"command": "ls"},
        )
        await pipe(tc3, [proc])
        tracer = _RecordingTracer()
        events = await pipe_all(
            ToolResultEvent(run_id="r1", step_id=2, tool_name="Bash", tool_call_id="c2", result="ok"),
            [proc],
            tracer=tracer,
            hook="after_tool",
        )
        # Warning text is injected into the tool result content
        result_events = [e for e in events if isinstance(e, ToolResultEvent)]
        assert result_events
        assert "[LoopDetection]" in result_events[-1].result
        assert "Bash" in result_events[-1].result
        # Auto-generated trigger goes to tracer
        trigs = tracer.trigger_events
        assert len(trigs) == 1
        assert trigs[0].processor == "LoopDetectionProcessor"
        assert trigs[0].action == "intervention"

    @pytest.mark.asyncio
    async def test_loop_detection_raise_on_threshold(self):
        """threshold=3: 3rd consecutive identical call raises LoopDetectedError."""
        proc = LoopDetectionProcessor(threshold=3, warn_threshold=2, window_size=10)
        for i in range(2):
            tc = ToolCallEvent(
                run_id="r1",
                step_id=i,
                tool_name="Bash",
                tool_call_id=f"c{i}",
                tool_input={"command": "ls"},
            )
            await pipe(tc, [proc])
            await pipe(
                ToolResultEvent(
                    run_id="r1",
                    step_id=i,
                    tool_name="Bash",
                    tool_call_id=f"c{i}",
                    result="ok",
                ),
                [proc],
            )
        tc3 = ToolCallEvent(
            run_id="r1",
            step_id=2,
            tool_name="Bash",
            tool_call_id="c2",
            tool_input={"command": "ls"},
        )
        await pipe(tc3, [proc])
        with pytest.raises(LoopDetectedError):
            await pipe_all(
                ToolResultEvent(
                    run_id="r1",
                    step_id=2,
                    tool_name="Bash",
                    tool_call_id="c2",
                    result="ok",
                ),
                [proc],
            )

    @pytest.mark.asyncio
    async def test_loop_detection_no_trigger_on_first_call(self):
        proc = LoopDetectionProcessor(threshold=5, warn_threshold=3, window_size=10)
        tc = ToolCallEvent(
            run_id="r1",
            step_id=0,
            tool_name="Bash",
            tool_call_id="c0",
            tool_input={"command": "ls"},
        )
        await pipe(tc, [proc])
        events = await pipe_all(
            ToolResultEvent(run_id="r1", step_id=0, tool_name="Bash", tool_call_id="c0", result="ok"),
            [proc],
        )
        assert _triggers(events) == []

    # =============================================================================
    # ToolFailureGuard
    # =============================================================================

    @pytest.mark.asyncio
    async def test_tool_failure_guard_warning_trigger(self):
        """max_failures=2, raise_on_exceed=False: at threshold injects warning into before_model messages."""
        proc = ToolFailureGuard(max_failures=2, raise_on_exceed=False)
        for i in range(2):
            await pipe(
                ToolResultEvent(
                    run_id="r1",
                    step_id=0,
                    tool_name="Bash",
                    tool_call_id=f"c{i}",
                    result="",
                    error="boom",
                ),
                [proc],
            )
        # step_start captures and resets the failure count; no injection here
        await pipe(StepStartEvent(run_id="r1", step_id=1), [proc])
        # before_model injects the warning
        tracer = _RecordingTracer()
        events = await pipe_all(
            BeforeModelEvent(
                run_id="r1",
                step_id=1,
                messages=(Message(role="user", content="t1"), Message(role="assistant", content="r1")),
            ),
            [proc],
            tracer=tracer,
            hook="before_model",
        )
        bm_events = [e for e in events if isinstance(e, BeforeModelEvent)]
        assert bm_events
        msgs = bm_events[-1].messages
        assert any("[ToolFailureGuard]" in (m.content if isinstance(m.content, str) else "") for m in msgs)
        # Auto-generated trigger goes to tracer
        trigs = tracer.trigger_events
        assert len(trigs) == 1
        assert trigs[0].processor == "ToolFailureGuard"
        assert trigs[0].action == "intervention"

    @pytest.mark.asyncio
    async def test_tool_failure_guard_halt_trigger(self):
        """max_failures=2, raise_on_exceed=True: at threshold raises ToolFailureLimitError at before_model."""
        proc = ToolFailureGuard(max_failures=2, raise_on_exceed=True)
        for i in range(2):
            await pipe(
                ToolResultEvent(
                    run_id="r1",
                    step_id=0,
                    tool_name="Bash",
                    tool_call_id=f"c{i}",
                    result="",
                    error="boom",
                ),
                [proc],
            )
        # step_start must succeed (only captures the count, does not raise)
        await pipe(StepStartEvent(run_id="r1", step_id=1), [proc])
        with pytest.raises(ToolFailureLimitError):
            await pipe_all(
                BeforeModelEvent(
                    run_id="r1",
                    step_id=1,
                    messages=(Message(role="user", content="t1"), Message(role="assistant", content="r1")),
                ),
                [proc],
            )

    @pytest.mark.asyncio
    async def test_tool_failure_guard_no_trigger_below_threshold(self):
        proc = ToolFailureGuard(max_failures=3, raise_on_exceed=False)
        await pipe(
            ToolResultEvent(
                run_id="r1",
                step_id=0,
                tool_name="Bash",
                tool_call_id="c0",
                result="",
                error="boom",
            ),
            [proc],
        )
        events = await pipe_all(StepStartEvent(run_id="r1", step_id=1), [proc])
        assert _triggers(events) == []

    # =============================================================================
    # SelfVerifyProcessor
    # =============================================================================

    @pytest.mark.asyncio
    async def test_self_verify_verification_triggered(self):
        """Exit-intent with writes pending → keepalive tool call injected into response."""
        proc = SelfVerifyProcessor()
        proc._write_count = 1  # simulate a file write without actually running Write tool
        event = ModelResponseEvent(run_id="r1", step_id=0, finish_reason="end_turn", tool_calls=())
        tracer = _RecordingTracer()
        events = await pipe_all(event, [proc], tracer=tracer, hook="after_model")
        # Keepalive tool call is injected into the model response
        model_events = [e for e in events if isinstance(e, ModelResponseEvent)]
        assert model_events
        assert len(model_events[-1].tool_calls) == 1
        assert model_events[-1].tool_calls[0].name == "_verify_keepalive"
        assert proc._pending_user_message != ""
        # Auto-generated trigger goes to tracer
        trigs = tracer.trigger_events
        assert len(trigs) == 1
        assert trigs[0].processor == "SelfVerifyProcessor"
        assert trigs[0].action == "intervention"

    @pytest.mark.asyncio
    async def test_self_verify_message_injected(self):
        """After verification triggered, before_model injects verification message into messages."""
        proc = SelfVerifyProcessor()
        proc._write_count = 1
        # First: trigger via on_after_model (sets _pending_user_message)
        await pipe(
            ModelResponseEvent(run_id="r1", step_id=0, finish_reason="end_turn", tool_calls=()),
            [proc],
        )
        # step_start is a pass-through (no injection here anymore)
        await pipe(StepStartEvent(run_id="r1", step_id=1), [proc])
        # before_model consumes the pending message
        tracer = _RecordingTracer()
        events = await pipe_all(
            BeforeModelEvent(
                run_id="r1",
                step_id=1,
                messages=(Message(role="user", content="t1"), Message(role="assistant", content="r1")),
            ),
            [proc],
            tracer=tracer,
            hook="before_model",
        )
        bm_events = [e for e in events if isinstance(e, BeforeModelEvent)]
        assert bm_events
        msgs = bm_events[-1].messages
        assert msgs and ("Before finishing" in msgs[-1].content or "final check" in msgs[-1].content.lower())
        # Auto-generated trigger goes to tracer
        trigs = tracer.trigger_events
        assert len(trigs) == 1
        assert trigs[0].processor == "SelfVerifyProcessor"
        assert trigs[0].action == "intervention"

    @pytest.mark.asyncio
    async def test_self_verify_no_trigger_without_writes(self):
        proc = SelfVerifyProcessor()
        event = ModelResponseEvent(run_id="r1", step_id=0, finish_reason="end_turn", tool_calls=())
        events = await pipe_all(event, [proc])
        assert _triggers(events) == []

    @pytest.mark.asyncio
    async def test_self_verify_no_trigger_when_tool_calls_present(self):
        """Model still calling tools → no verification yet."""
        proc = SelfVerifyProcessor()
        proc._write_count = 1
        tc = ToolCall(id="tc1", name="Bash", input={"command": "echo"})
        event = ModelResponseEvent(run_id="r1", step_id=0, finish_reason="end_turn", tool_calls=(tc,))
        events = await pipe_all(event, [proc])
        assert _triggers(events) == []

    @pytest.mark.asyncio
    async def test_self_verify_ignore_memory_write_path(self):
        proc = SelfVerifyProcessor()
        await pipe(
            ToolCallEvent(
                run_id="r1",
                step_id=0,
                tool_name="Write",
                tool_call_id="w1",
                tool_input={"file_path": str(Path.home() / ".harnessx" / "memory" / "user" / "profile.md")},
            ),
            [proc],
        )
        events = await pipe_all(
            ModelResponseEvent(run_id="r1", step_id=1, finish_reason="end_turn", tool_calls=()),
            [proc],
        )
        assert _triggers(events) == []

    @pytest.mark.asyncio
    async def test_self_verify_count_project_write_path(self):
        proc = SelfVerifyProcessor()
        await pipe(
            ToolCallEvent(
                run_id="r1",
                step_id=0,
                tool_name="Write",
                tool_call_id="w2",
                tool_input={"file_path": "/tmp/example_output.txt"},
            ),
            [proc],
        )
        events = await pipe_all(
            ModelResponseEvent(run_id="r1", step_id=1, finish_reason="end_turn", tool_calls=()),
            [proc],
        )
        # Keepalive is injected because a project-relevant write was counted
        model_events = [e for e in events if isinstance(e, ModelResponseEvent)]
        assert model_events
        assert any(tc.name == "_verify_keepalive" for tc in model_events[-1].tool_calls)

    # =============================================================================
    # ParseRetryProcessor
    # =============================================================================

    @pytest.mark.asyncio
    async def test_parse_retry_raises_on_malformed_tool_call(self):
        """Empty tool name triggers parse_error_raise and ModelParseError."""
        proc = ParseRetryProcessor(max_consecutive_errors=1)
        bad_tc = ToolCall(id="bad", name="", input={})
        event = ModelResponseEvent(run_id="r1", step_id=0, tool_calls=(bad_tc,))
        with pytest.raises(ModelParseError):
            await pipe_all(event, [proc])

    @pytest.mark.asyncio
    async def test_parse_retry_no_trigger_on_valid_response(self):
        proc = ParseRetryProcessor()
        good_tc = ToolCall(id="ok", name="Bash", input={"command": "ls"})
        event = ModelResponseEvent(run_id="r1", step_id=0, tool_calls=(good_tc,))
        events = await pipe_all(event, [proc])
        assert _triggers(events) == []

    @pytest.mark.asyncio
    async def test_parse_retry_tolerates_errors_below_threshold(self):
        """max_consecutive_errors=2: first error just increments counter, no raise."""
        proc = ParseRetryProcessor(max_consecutive_errors=2)
        bad_tc = ToolCall(id="bad", name="", input={})
        event = ModelResponseEvent(run_id="r1", step_id=0, tool_calls=(bad_tc,))
        # First error: below threshold — should NOT raise, just yield the event
        result = await pipe(event, [proc])
        assert result is not None
        assert proc._error_counts.get("r1") == 1

    @pytest.mark.asyncio
    async def test_parse_retry_per_run_id_isolation(self):
        """Singleton: a valid response from run B must not reset run A's counter."""
        proc = ParseRetryProcessor(max_consecutive_errors=2)
        bad_tc = ToolCall(id="bad", name="", input={})
        good_tc = ToolCall(id="ok", name="Bash", input={"command": "ls"})

        # Run A gets a malformed response — counter reaches 1
        await pipe(ModelResponseEvent(run_id="run-a", step_id=0, tool_calls=(bad_tc,)), [proc])
        assert proc._error_counts.get("run-a") == 1

        # Run B gets a valid response — must NOT touch run A's counter
        await pipe(ModelResponseEvent(run_id="run-b", step_id=0, tool_calls=(good_tc,)), [proc])
        assert proc._error_counts.get("run-b") is None  # cleaned up on valid
        assert proc._error_counts.get("run-a") == 1  # run A unchanged

        # Run A gets a second malformed response — now raises
        with pytest.raises(ModelParseError):
            await pipe(ModelResponseEvent(run_id="run-a", step_id=1, tool_calls=(bad_tc,)), [proc])
        assert proc._error_counts.get("run-a") is None  # cleaned up after raise

    # =============================================================================
    # ToolCallCorrectionLayer
    # =============================================================================

    @pytest.mark.asyncio
    async def test_tool_call_correction_params_corrected_trigger(self):
        """Boolean string coercion corrects the event; auto-trigger goes to tracer."""
        proc = ToolCallCorrectionLayer(
            tool_schemas={"MyTool": {"properties": {"flag": {"type": "boolean"}}}},
        )
        event = ToolCallEvent(
            run_id="r1",
            step_id=0,
            tool_name="MyTool",
            tool_call_id="c1",
            tool_input={"flag": "true"},
        )
        tracer = _RecordingTracer()
        events = await pipe_all(event, [proc], tracer=tracer, hook="before_tool")
        # Corrected event should have True (bool), not "true" (str)
        corrected = [e for e in events if isinstance(e, ToolCallEvent)]
        assert len(corrected) == 1
        assert corrected[0].tool_input["flag"] is True
        # Auto-generated trigger goes to tracer
        trigs = tracer.trigger_events
        assert len(trigs) == 1
        assert trigs[0].processor == "ToolCallCorrectionLayer"
        assert trigs[0].hook == "before_tool"
        assert trigs[0].action == "intervention"

    @pytest.mark.asyncio
    async def test_tool_call_correction_no_trigger_when_no_change(self):
        proc = ToolCallCorrectionLayer()
        event = ToolCallEvent(
            run_id="r1",
            step_id=0,
            tool_name="Bash",
            tool_call_id="c1",
            tool_input={"command": "ls"},
        )
        events = await pipe_all(event, [proc])
        assert _triggers(events) == []

    # =============================================================================
    # CostGuardProcessor
    # =============================================================================

    @pytest.mark.asyncio
    async def test_cost_guard_warning_threshold(self):
        """Cost at 85 % of limit logs a warning but passes the event through unchanged."""
        proc = CostGuardProcessor(max_usd=1.0, warning_threshold=0.8)
        event = BeforeModelEvent(run_id="r1", step_id=0, cumulative_cost_usd=0.85)
        events = await pipe_all(event, [proc])
        # Event passes through — no modification, no trigger
        bm_events = [e for e in events if isinstance(e, BeforeModelEvent)]
        assert len(bm_events) == 1
        assert bm_events[0].cumulative_cost_usd == 0.85
        assert _triggers(events) == []

    @pytest.mark.asyncio
    async def test_cost_guard_halt_raises(self):
        proc = CostGuardProcessor(max_usd=1.0)
        event = BeforeModelEvent(run_id="r1", step_id=0, cumulative_cost_usd=1.5)
        with pytest.raises(BudgetExceededError):
            await pipe_all(event, [proc])

    @pytest.mark.asyncio
    async def test_cost_guard_no_trigger_under_threshold(self):
        proc = CostGuardProcessor(max_usd=1.0, warning_threshold=0.8)
        event = BeforeModelEvent(run_id="r1", step_id=0, cumulative_cost_usd=0.5)
        events = await pipe_all(event, [proc])
        assert _triggers(events) == []

    # =============================================================================
    # RepeatedFileEditDetector
    # =============================================================================

    @pytest.mark.asyncio
    async def test_repeated_edit_soft_trigger(self):
        """3rd edit → soft hint appended to tool result."""
        proc = RepeatedFileEditDetector(soft_threshold=3, hard_threshold=7)
        for i in range(2):
            await _write_file(proc, "/f.py", f"id{i}")
        events = await _write_file(proc, "/f.py", "id2")
        result_events = [e for e in events if isinstance(e, ToolResultEvent)]
        assert result_events
        assert "[RepeatedFileEditDetector]" in result_events[-1].result
        assert "/f.py" in result_events[-1].result
        assert "3 times" in result_events[-1].result

    @pytest.mark.asyncio
    async def test_repeated_edit_hard_trigger(self):
        """5th edit → hard hint appended to tool result."""
        proc = RepeatedFileEditDetector(soft_threshold=3, hard_threshold=5)
        for i in range(4):
            await _write_file(proc, "/f.py", f"id{i}")
        events = await _write_file(proc, "/f.py", "id4")
        result_events = [e for e in events if isinstance(e, ToolResultEvent)]
        assert result_events
        assert "[RepeatedFileEditDetector]" in result_events[-1].result
        assert "5 times" in result_events[-1].result

    @pytest.mark.asyncio
    async def test_repeated_edit_no_trigger_below_soft(self):
        proc = RepeatedFileEditDetector(soft_threshold=5, hard_threshold=10)
        events = await _write_file(proc, "/f.py", "id0")
        assert _triggers(events) == []

    # =============================================================================
    # TokenBudgetProcessor
    # =============================================================================

    @pytest.mark.asyncio
    async def test_token_budget_context_truncated_trigger(self):
        proc = TokenBudgetProcessor(ratio=0.8)
        msgs = tuple(Message(role="user", content=f"msg {i}") for i in range(50))
        event = StepStartEvent(run_id="r1", step_id=0, messages=msgs, token_count=500, context_window=100)
        tracer = _RecordingTracer()
        events = await pipe_all(event, [proc], tracer=tracer, hook="step_start")
        # Context was actually truncated
        step_events = [e for e in events if isinstance(e, StepStartEvent)]
        assert len(step_events[-1].messages) < len(msgs)
        # Auto-generated trigger goes to tracer
        trigs = tracer.trigger_events
        assert len(trigs) == 1
        assert trigs[0].processor == "TokenBudgetProcessor"
        assert trigs[0].hook == "step_start"
        assert trigs[0].action == "intervention"

    @pytest.mark.asyncio
    async def test_token_budget_no_trigger_under_budget(self):
        proc = TokenBudgetProcessor(ratio=0.8)
        event = StepStartEvent(
            run_id="r1",
            step_id=0,
            messages=(Message(role="user", content="hi"),),
            token_count=50,
            context_window=100,
        )
        events = await pipe_all(event, [proc])
        assert _triggers(events) == []

    # =============================================================================
    # BgInstallGuard
    # =============================================================================

    @pytest.mark.asyncio
    async def test_bg_install_guard_blocked_trigger(self):
        proc = BgInstallGuard()
        event = ToolCallEvent(
            run_id="r1",
            step_id=0,
            tool_name="Bash",
            tool_call_id="c1",
            tool_input={"command": "apt-get install curl &"},
        )
        tracer = _RecordingTracer()
        events = await pipe_all(event, [proc], tracer=tracer, hook="before_tool")
        # The ToolCallEvent in results should be blocked
        blocked = [e for e in events if isinstance(e, ToolCallEvent)]
        assert len(blocked) == 1
        assert blocked[0].approved is False
        assert blocked[0].synthetic_result is not None
        # Auto-generated trigger goes to tracer
        trigs = tracer.trigger_events
        assert len(trigs) == 1
        assert trigs[0].processor == "BgInstallGuard"
        assert trigs[0].hook == "before_tool"
        assert trigs[0].action == "intervention"

    @pytest.mark.asyncio
    async def test_bg_install_guard_no_trigger_on_safe_command(self):
        proc = BgInstallGuard()
        event = ToolCallEvent(
            run_id="r1",
            step_id=0,
            tool_name="Bash",
            tool_call_id="c1",
            tool_input={"command": "apt-get install curl"},
        )  # no backgrounding
        events = await pipe_all(event, [proc])
        assert _triggers(events) == []

    @pytest.mark.asyncio
    async def test_bg_install_guard_no_trigger_for_non_bash(self):
        proc = BgInstallGuard()
        event = ToolCallEvent(
            run_id="r1",
            step_id=0,
            tool_name="Read",
            tool_call_id="c1",
            tool_input={"file_path": "/etc/apt/sources.list"},
        )
        events = await pipe_all(event, [proc])
        assert _triggers(events) == []

    # =============================================================================
    # TodoCheck (passive incomplete-todo reminder)
    # =============================================================================

    @pytest.mark.asyncio
    async def test_todo_check_no_reminder_without_todos(self):
        """No todo_write called yet → step_start passes through with no injection."""
        proc = TodoCheck()
        events = await pipe_all(StepStartEvent(run_id="r1", step_id=1), [proc])
        assert _triggers(events) == []
        step_events = [e for e in events if isinstance(e, StepStartEvent)]
        assert step_events[-1].messages == ()

    @pytest.mark.asyncio
    async def test_todo_check_no_reminder_when_tools_were_called(self):
        """Todos exist but the last step had tool calls → no reminder injected."""
        proc = TodoCheck()
        proc._todos = list(_TODOS_MIX)
        proc._step_had_tools = True  # simulates a step that called tools
        events = await pipe_all(StepStartEvent(run_id="r1", step_id=2), [proc])
        assert _triggers(events) == []
        step_events = [e for e in events if isinstance(e, StepStartEvent)]
        assert step_events[-1].messages == ()

    @pytest.mark.asyncio
    async def test_todo_check_reminder_injected_after_tool_free_step(self):
        """Todos exist + last step had no tool calls → reminder message injected into before_model messages."""
        proc = TodoCheck()
        proc._todos = list(_TODOS_MIX)
        proc._step_had_tools = False  # tool-free step just ended
        # step_start captures state (_no_tools_last_step); no injection here
        await pipe(StepStartEvent(run_id="r1", step_id=2), [proc])
        # before_model injects the reminder
        tracer = _RecordingTracer()
        events = await pipe_all(
            BeforeModelEvent(
                run_id="r1",
                step_id=2,
                messages=(Message(role="user", content="t1"), Message(role="assistant", content="r1")),
            ),
            [proc],
            tracer=tracer,
            hook="before_model",
        )
        bm_events = [e for e in events if isinstance(e, BeforeModelEvent)]
        msg = bm_events[-1].messages[-1]
        assert msg.role == "user"
        assert "Write report" in msg.content  # in_progress item listed
        assert "Review draft" in msg.content  # pending item listed
        assert "Research topic" not in msg.content  # done item excluded
        # Auto-generated trigger goes to tracer
        trigs = tracer.trigger_events
        assert len(trigs) == 1
        assert trigs[0].processor == "TodoCheck"
        assert trigs[0].action == "intervention"

    @pytest.mark.asyncio
    async def test_todo_check_no_reminder_when_all_done(self):
        """All todos are done → no reminder even after a tool-free step."""
        proc = TodoCheck()
        proc._todos = list(_TODOS_ALL_DONE)
        proc._step_had_tools = False
        events = await pipe_all(StepStartEvent(run_id="r1", step_id=2), [proc])
        assert _triggers(events) == []

    @pytest.mark.asyncio
    async def test_todo_check_write_not_blocked(self):
        """Write tool must never be blocked regardless of todo state (passive design)."""
        proc = TodoCheck()
        # even with no todos written at all, Write goes through freely
        event = ToolCallEvent(
            run_id="r1",
            step_id=0,
            tool_name="Write",
            tool_call_id="c1",
            tool_input={"file_path": "/x.py"},
        )
        events = await pipe_all(event, [proc])
        assert _triggers(events) == []
        blocked = [e for e in events if isinstance(e, ToolCallEvent)]
        assert blocked[0].approved is True

    @pytest.mark.asyncio
    async def test_todo_check_captures_todos_from_tool_call(self):
        """on_before_tool with todo_write captures the todo list for future reminder checks."""
        proc = TodoCheck()
        event = ToolCallEvent(
            run_id="r1",
            step_id=0,
            tool_name="todo_write",
            tool_call_id="c1",
            tool_input={"todos": _TODOS_MIX},
        )
        await pipe_all(event, [proc])
        assert len(proc._todos) == 3
        assert proc._step_had_tools is True

    # =============================================================================
    # RLSignalCollectorProcessor
    # =============================================================================

    @pytest.mark.asyncio
    async def test_rl_signal_loop_detected(self):
        """Same fingerprint 2+ times in window → loop_step_ids updated; loop_detected flag set."""
        proc = RLSignalCollectorProcessor()
        # Seed the window: same summary twice in first _WINDOW steps
        for i in range(2):
            await pipe(
                StepEndEvent(run_id="r1", step_id=i, tool_call_summary="Bash(ls)"),
                [proc],
            )
        # Third occurrence → recent.count >= 2 → loop detected
        await pipe_all(StepEndEvent(run_id="r1", step_id=2, tool_call_summary="Bash(ls)"), [proc])
        assert proc.loop_detected
        assert 2 in proc.loop_step_ids

    @pytest.mark.asyncio
    async def test_rl_signal_loop_raise_trigger(self):
        """Step after loop_detected → loop_raise trigger then LoopDetectedError."""
        proc = RLSignalCollectorProcessor()
        for i in range(2):
            await pipe(
                StepEndEvent(run_id="r1", step_id=i, tool_call_summary="Bash(ls)"),
                [proc],
            )
        await pipe(StepEndEvent(run_id="r1", step_id=2, tool_call_summary="Bash(ls)"), [proc])
        # Next step_id=3: loop was detected at step 2, 3 == 2+1 → raise
        with pytest.raises(LoopDetectedError):
            await pipe_all(BeforeModelEvent(run_id="r1", step_id=3), [proc])

    @pytest.mark.asyncio
    async def test_rl_signal_no_trigger_on_varied_summaries(self):
        proc = RLSignalCollectorProcessor()
        for i in range(5):
            events = await pipe_all(
                StepEndEvent(run_id="r1", step_id=i, tool_call_summary=f"Bash(cmd{i})"),
                [proc],
            )
            assert _triggers(events) == []

    # =============================================================================
    # SycophancyDetector
    # =============================================================================

    @pytest.mark.asyncio
    async def test_sycophancy_contrarian_pending(self):
        """Three consecutive agreeing responses → contrarian_pending flag set."""
        proc = SycophancyDetector(streak_threshold=3)
        # 3 consecutive sycophantic responses
        for i in range(2):
            await pipe(_agree_event(step_id=i), [proc])
        await pipe_all(_agree_event(step_id=2), [proc])
        assert proc._contrarian_pending is True
        assert proc._agree_streak == 0  # reset after triggering

    @pytest.mark.asyncio
    async def test_sycophancy_contrarian_injected(self):
        """After contrarian_pending is set, before_model injects contrarian block into messages."""
        proc = SycophancyDetector(streak_threshold=3)
        proc._contrarian_pending = True
        proc._task_mode = False
        events = await pipe_all(
            BeforeModelEvent(
                run_id="r1",
                step_id=1,
                messages=(Message(role="user", content="t1"), Message(role="assistant", content="r1")),
            ),
            [proc],
            hook="before_model",
        )
        bm_events = [e for e in events if isinstance(e, BeforeModelEvent)]
        assert "CONTRARIAN" in bm_events[-1].messages[-1].content

    @pytest.mark.asyncio
    async def test_sycophancy_no_trigger_below_streak_threshold(self):
        proc = SycophancyDetector(streak_threshold=3)
        events = await pipe_all(_agree_event(), [proc])
        assert _triggers(events) == []

    @pytest.mark.asyncio
    async def test_sycophancy_no_trigger_on_non_agreeing_response(self):
        proc = SycophancyDetector(streak_threshold=3)
        event = ModelResponseEvent(run_id="r1", step_id=0, content="I disagree with that.")
        events = await pipe_all(event, [proc])
        assert _triggers(events) == []

    # =============================================================================
    # Auto-detection mechanism (ProcessorChain)
    # =============================================================================
    # ProcessorChain detects when a processor modifies the primary event and sends
    # a ProcessorTriggerEvent to the tracer.  The trigger is NOT in the events list.

    @pytest.mark.asyncio
    async def test_auto_detect_emits_intervention_on_mutation(self):
        """ProcessorChain detects event mutation and sends trigger to tracer."""
        proc = _MutatingProcessor()
        event = BeforeModelEvent(run_id="r1", step_id=0)
        tracer = _RecordingTracer()
        events = await pipe_all(event, [proc], tracer=tracer, hook="before_model")
        # Trigger goes to tracer, NOT in the events list
        assert _triggers(events) == []
        trigs = tracer.trigger_events
        assert len(trigs) == 1
        assert trigs[0].processor == "_MutatingProcessor"
        assert trigs[0].hook == "before_model"
        assert trigs[0].action == "intervention"
        assert trigs[0].detail == {}

    @pytest.mark.asyncio
    async def test_auto_detect_no_trigger_on_passthrough(self):
        """A processor that yields the input event unchanged emits no trigger."""
        proc = _PassthroughProcessor()
        event = BeforeModelEvent(run_id="r1", step_id=0)
        tracer = _RecordingTracer()
        events = await pipe_all(event, [proc], tracer=tracer, hook="before_model")
        assert _triggers(events) == []
        assert tracer.trigger_events == []
